In [2]:
import numpy as np

# np.arange
Can create an array

In [4]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


# Operation with each element
Usually, to operate with each element of an array we do this:
```python
for i in range(len(arr)):
    arr[i] *= 2
```
While this is easy but it takes time. Numpy can do this faster and can be done like this:

In [5]:
x = x*2
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
x = [[1,2,0], [1,0,3], [0,4,5]]
x = np.array(x)
x

array([[1, 2, 0],
       [1, 0, 3],
       [0, 4, 5]])

In [12]:
y = np.sum(x[:,1])
print(y)
x[:,1]

6


array([2, 0, 4])

In [13]:
x[1,:]

array([1, 0, 3])

In [18]:
x = [[1,0,0,1,1]]
y = [[0,1,1,1,0], [1,0,0,1,0]]
x = np.array(x)
y = np.array(y)
z = np.concatenate((x,y))
print(z)

[[1 0 0 1 1]
 [0 1 1 1 0]
 [1 0 0 1 0]]


In [ ]:
l = len(x)
    point = np.random.randint(1, l)
    print(point)
    off1 = np.concatenate((x[point:], y[:point]))
    off2 = np.concatenate((y[point:], x[:point]))
    